baseURL = "https://blog.nikchester.lat/"
languageCode = "ru"
title = "Chesterfield"
theme = "papermode"

[params]
  homeInfoParams = { Title = "Блог Никиты Чатурова aka nikchester", Content = "Здрасте! Здесь я делюсь интересными мыслями, материалами и знаниями." }
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  socialIcons = [
    { name = "telegram", url = "https://t.me/Chesterf1ld" },
    { name = "github", url = "https://github.com/Chest3rf1eld" }
  ]
  favicon = "/favicon.ico"

[[menu.main]]
  name = "Посты"
  url = "/posts/"
  weight = 1
